version: 2.1
jobs:
  build:
    docker:
      - image: 'emscripten/emsdk:2.0.9'
    resource_class: xlarge

    working_directory: ~/checkout

    steps:
      - checkout

      - run:
          name: Build Bergamot Translator WASM artifacts
          command: bash bergamot-translator/build-wasm.sh

      - run:
          name: Import and concatenate Bergamot Translator WASM artifacts with bergamot-translator-worker.appendix.js
          command: cd extension && ./import-bergamot-translator.sh ../bergamot-translator/build-wasm/wasm/

      - store_artifacts:
          path: "extension/src/wasm"
          destination: "extension/src/wasm"
